import React from 'react';
import { Graph, FlowData, MindData, GraphReactEventProps } from '../../common/interfaces';
import { EditorPrivateContextProps } from '../EditorContext';
import './behavior';
interface GraphProps extends Partial<GraphReactEventProps>, EditorPrivateContextProps {
  style?: React.CSSProperties;
  className?: string;
  containerId: string;
  data: FlowData | MindData;
  parseData(data: object): void;
  initGraph(width: number, height: number): Graph;
}
declare const _default: React.ForwardRefExoticComponent<Pick<
  React.PropsWithChildren<GraphProps>,
  | 'onClick'
  | 'onDoubleClick'
  | 'onMouseEnter'
  | 'onMouseMove'
  | 'onMouseOut'
  | 'onMouseOver'
  | 'onMouseLeave'
  | 'onMouseDown'
  | 'onMouseUp'
  | 'onContextMenu'
  | 'onDragStart'
  | 'onDrag'
  | 'onDragEnd'
  | 'onDragEnter'
  | 'onDragLeave'
  | 'onDrop'
  | 'onKeyDown'
  | 'onKeyUp'
  | 'onTouchStart'
  | 'onTouchMove'
  | 'onTouchEnd'
  | 'onNodeClick'
  | 'onNodeDoubleClick'
  | 'onNodeMouseEnter'
  | 'onNodeMouseMove'
  | 'onNodeMouseOut'
  | 'onNodeMouseOver'
  | 'onNodeMouseLeave'
  | 'onNodeMouseDown'
  | 'onNodeMouseUp'
  | 'onNodeContextMenu'
  | 'onNodeDragStart'
  | 'onNodeDrag'
  | 'onNodeDragEnd'
  | 'onNodeDragEnter'
  | 'onNodeDragLeave'
  | 'onNodeDrop'
  | 'onEdgeClick'
  | 'onEdgeDoubleClick'
  | 'onEdgeMouseEnter'
  | 'onEdgeMouseMove'
  | 'onEdgeMouseOut'
  | 'onEdgeMouseOver'
  | 'onEdgeMouseLeave'
  | 'onEdgeMouseDown'
  | 'onEdgeMouseUp'
  | 'onEdgeContextMenu'
  | 'onCanvasClick'
  | 'onCanvasDoubleClick'
  | 'onCanvasMouseEnter'
  | 'onCanvasMouseMove'
  | 'onCanvasMouseOut'
  | 'onCanvasMouseOver'
  | 'onCanvasMouseLeave'
  | 'onCanvasMouseDown'
  | 'onCanvasMouseUp'
  | 'onCanvasContextMenu'
  | 'onCanvasDragStart'
  | 'onCanvasDrag'
  | 'onCanvasDragEnd'
  | 'onCanvasDragEnter'
  | 'onCanvasDragLeave'
  | 'onBeforeAddItem'
  | 'onAfterAddItem'
  | 'onBeforeRemoveItem'
  | 'onAfterRemoveItem'
  | 'onBeforeUpdateItem'
  | 'onAfterUpdateItem'
  | 'onBeforeItemVisibilityChange'
  | 'onAfterItemVisibilityChange'
  | 'onBeforeItemStateChange'
  | 'onAfterItemStateChange'
  | 'onBeforeRefreshItem'
  | 'onAfterRefreshItem'
  | 'onBeforeItemStatesClear'
  | 'onAfterItemStatesClear'
  | 'onBeforeLayout'
  | 'onAfterLayout'
  | 'onAfterConnect'
  | 'style'
  | 'className'
  | 'containerId'
  | 'data'
  | 'parseData'
  | 'initGraph'
  | 'children'
> &
  React.RefAttributes<unknown>>;
export default _default;
